create database customer_behaviour;

USE customer_behaviour;

-- Q1. What is the total revenue generated by the Male and Female Customers?
select gender,sum(purchase_amount) as revenue
from customer 
group by gender;

select * from customer limit 10;

-- Q2. Which customers used discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the Avergae Purchases Amount between Standard and Express Shipping?
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in ("Standard","Express")
group by shipping_type;

-- Q5. Do subscribed customer spend more? Compare average spend and total revenue between Subscriber and Non-Subscriber?
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend;

-- Q6. Which 5 product has the highest percentage of purchases with discount applied?
select item_purchased,
round(sum(case when discount_applied = "Yes" Then 1 Else 0 End)/Count(*) * 100,2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment Customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
Case
   When previous_purchases = 1 Then "New"
   When previous_purchases between 2 and 10 then "Returning"
   Else "Loyal"
   End as customer_segment
from customer
   )

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment; 

-- Q8. What are the top 3 most purchased product from each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <= 3;

-- Q9. Are Customers who are repeat buyers(more than 5 previous purchases) also likely to suscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

describe customer;

-- Q10. What is the contribution revenue of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
